

= Einordnung webpack vs gulp vs browserify

https://www.toptal.com/front-end/webpack-browserify-gulp-which-is-better



= metal-examples-custom-build-webpack
A simple component using soy templates and webpack.

Since this example is a soy component, it needs to use Metal.js's custom logic for compiling soy templates so they can be integrated with the appropriate Component class. This example uses [metal-cli](http://www.npmjs.com/package/metal-cli) to compile the templates before bundling the code via webpack.

The webpack command is included in the `build` script, so take a look at package.json to check it out. Note that we're using [babel-loader](http://www.npmjs.com/package/babel-loader) to compile the ES6 code.

The code has lots of comments explaining how everything works.

## Setup

1. Install NodeJS >= [v0.12.0](http://nodejs.org/dist/v0.12.0/), if you don't have it yet.

2. Install local dependencies:

  ```
  npm install
  ```

3. Build the code:

  ```
  npm run build
  ```

4. Open the demo at demos/index.html on your browser.


= Gradle Node Plugin

https://github.com/srs/gradle-node-plugin/blob/master/docs/node.md



All npm command can also be invoked using underscore notation based on a gradle rule:

$ gradle npm_install
$ gradle npm_update
$ gradle npm_list
$ gradle npm_cache_clean

These however are not shown when running gradle tasks, as they generated dynamically. However they can be used for dependency declarations, such as:

npm_install.dependsOn(npm_cache_clean)
More arguments can be passed via the build.gradle file:

npm_update {
  args = ['--production', '--loglevel', 'warn']
}
If you want to extend the tasks more or create custom variants, you can extend the class NpmTask:

task installExpress(type: NpmTask) {
  // install the express package only
  args = ['install', 'express', '--save-dev']
}















= LiveReload HTML Example

An example project that demonstrates how to convert AsciiDoc to HTML5 using the Asciidoctor Gradle plugin with http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/#livereload[Live Reload] support.

== Usage

Convert the AsciiDoc to HTML5 by invoking the 'asciidoctor' goal:

 $ ./gradlew asciidoctor

Open the file _build/asciidoc/html/example-manual.html_  in your browser to see the generated HTML file.

== Live Reload Support

The Gradle build also can support http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/#livereload[Live Reload]

Start by running the build with Gradle 2.5+ https://docs.gradle.org/2.5/userguide/continuous_build.html[continuous build] feature.

 $ ./gradlew -t asciidoctor

This ensures if you modify example-manual.adoc then everything is rebuilt.

Open another terminal and run the liveReload task:

 $ ./gradlew liveReload

Now you can use the https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en[Chrome] or http://feedback.livereload.com/knowledgebase/articles/86242-how-do-i-install-and-use-the-browser-extensions-[Firefox] plugins to automatically reload your browser when the build completes.

IMPORTANT: After installing the Chrome LiveReload extension, you need to check the "Allow access to file URLs" checkbox in Tools > Extensions > LiveReload in order for it to work with local files.

Now try editing example-manual.adoc and watching your browser.
After a brief wait you will observe that the browser is automatically updated with your changes.