



= metal-examples-custom-build-webpack
A simple component using soy templates and webpack.

Since this example is a soy component, it needs to use Metal.js's custom logic for compiling soy templates so they can be integrated with the appropriate Component class. This example uses [metal-cli](http://www.npmjs.com/package/metal-cli) to compile the templates before bundling the code via webpack.

The webpack command is included in the `build` script, so take a look at package.json to check it out. Note that we're using [babel-loader](http://www.npmjs.com/package/babel-loader) to compile the ES6 code.

The code has lots of comments explaining how everything works.

## Setup

1. Install NodeJS

2. Install local dependencies:

  ```
  npm install
  ```

3. Run webdev server and check http://localhost:9001
 ```
	npm run start
  ```
  
  
4. Build the code:

  ```
  npm run build
  ```




= Gradle Node Plugin

https://github.com/srs/gradle-node-plugin/blob/master/docs/node.md



All npm command can also be invoked using underscore notation based on a gradle rule:

$ gradle npm_install
$ gradle npm_update
$ gradle npm_list
$ gradle npm_cache_clean

These however are not shown when running gradle tasks, as they generated dynamically. However they can be used for dependency declarations, such as:

npm_install.dependsOn(npm_cache_clean)
More arguments can be passed via the build.gradle file:

npm_update {
  args = ['--production', '--loglevel', 'warn']
}
If you want to extend the tasks more or create custom variants, you can extend the class NpmTask:

task installExpress(type: NpmTask) {
  // install the express package only
  args = ['install', 'express', '--save-dev']
}






